### ISSUE TITLE
Certain tracks just won't finish

### ISSUE THREAD

**Issue by williammuff** [GuillemCastro/spotify-dl#10]
6Yimrlg9ndHZUy1hGm6uQ9 for example. 10 second timeout appears to be reached and a file isn't created.

**Comment by RuinedYourLife** [comment]
can confirm, no 10s timeout on my side though, i'd say for a solid second it shows the download, and then just dies out.
i have no idea what the issue is atm, i'll try to see if i can find anything

https://github.com/GuillemCastro/spotify-dl/assets/35805569/3d937859-7b21-4f13-bbc7-24773ee1ca12

**Comment by builtbybrayne** [comment]
I've also got this problem.

I know zero Rust (though have been coding since the dinosaurs), so have been ChatGPTing this and working it through.

I've tried wrapping the inner loop for each track handling in a function that is trying to catch and handle panics:

```
for (i, track) in tracks.iter().enumerate() {
        eprintln!("Downloading track {}/{}", i + 1, tracks.len());
        .... some cloning and Arc protection for params ....
         let result = panic::catch_unwind(AssertUnwindSafe(|| {
                  .... more cloning and Arc protection for params ....
                tokio::spawn(async move {
                    handle_track(i, track_id, session_clone, destination_clone, ordered, compression, &player_config_clone).await
                })
            }));

            match result {
                Ok(join_handle) => match join_handle.await {
                    Ok(Ok(_)) => println!("<-- OK"),
                    Ok(Err(e)) => println!("<-- Error handling track: {:?}", e),
                    Err(_) => println!("<-- Join handle dropped or error"),
                },
                Err(_) => println!("<-- Panic occurred while handling track"),
            }


        bar.inc(1);
        eprintln!("Track {}/{} done", i + 1, tracks.len());
    }
```

This has not worked.

I have though identified that the problem line is:

```
player.await_end_of_track().await
```

This, for some tracks, just kills the entire process.

I've run out of GPT4 allowance now, so am posting this as WIP on finding a solution. (GPT3.5 doesn't stand a chance)

**Comment by builtbybrayne** [comment]
I also now tried this:

```
 let await_result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                tokio::spawn(async move {
                    let player_config = PlayerConfig::default();
                    let session = create_session(credentials_clone).await;

                    let (mut player, _) =
                        Player::new(player_config, session, None, move || {
                            Box::new(file_sink)
                        });
                    player.load(*track_id_cloned.as_ref(), true, 0);  // Dereference Arc to get SpotifyId
                    player.await_end_of_track().await;
                    player.stop();
                })
            }));

            match await_result {
                Ok(join_handle) => {
                    // The function did not panic
                    // Now we need to await the JoinHandle
                    match join_handle.await {
                        Ok(_) => {
                            eprintln!("--> Done {}/{}", i + 1, tracks.len());
                            // The future completed successfully
                        },
                        Err(err) => {
                            // The future panicked
                            eprintln!("Error: await_end_of_track panicked: {:?}", err);
                        }
                    }
                },
                Err(_) => {
                    // The function did panic, but we're swallowing the panic here
                    eprintln!("Error: catch_unwind panicked");
                }
            }
```

Still silently failing

**Comment by williammuff** [comment]
Seems like it has something to do with the libspot library. I just wish i knew how to turn on verbose logging (if that's even an option in the libspot library).

**Comment by RuinedYourLife** [comment]
i tracked it down to the same line you pointed @builtbybrayne 
i updated librespot inside my fork but to no avail
the tracks that did not work for me now are working, so it could be a spotify thing
did not investigate any further, will try when i got time (:

**Comment by builtbybrayne** [comment]
So, I finally got this working.

A) I updated librespot to 0.4.2

B) I removed all Tokio async, including on main. Wherever I needed an await I wrapped in a blocking call (via Tokio Runtime). (I can afford to do this as I don't care about performance for my use-case).

I also did a bunch of other stuff, but I think those were the only relevant changes.

It's entirely possible it was only the librespot update that solved it. 

My hunch is that there was a direct process abort on some internal condition. I'm not very knowledgeable about Rust but I gather this is a thing when panics are not possible/acceptable. Updating the library didn't change the outcome to a panic though. It just started working and the songs that were failing now work fine. 

It's possible that a problematic async architecture under the hood means that my blocking sync approach has _also_ avoided triggering some underlying conflict. Hence I've mentioned it, as you may need to do both.

**Comment by williammuff** [comment]
Could you share your main.rs?

**Comment by GuillemCastro** [comment]
I have updated some dependencies, you can try and check if it's working for you now.

> --- Edit ---- Here's an example track that consistently fails for me: [https://open.spotify.com/track/7y0tcZwJwE8V4z8U5aOsWr\?si\=9a3e8974a45b4f8](https://open.spotify.com/track/7y0tcZwJwE8V4z8U5aOsWr%5C?si%5C=9a3e8974a45b4f8)

I have tried with this one and it seems to work
