### ISSUE TITLE
Add mp3 support

### ISSUE THREAD

**Issue by derblub** [GuillemCastro/spotify-dl#5]
I'm trying to implement mp3 support by using "Syphonia" crate. I've added a new option-switch, but unfortunately, my build is failing in the [modified file_sink](https://github.com/derblub/spotify-dl/blob/mp3-support/src/file_sink.rs) and I have no idea why (that's why no pull-request yet). Can you help out? Have you ever used that crate before?

**Comment by dbalague** [comment]
I know of at least one written in Python (search for spotify-dlx on GitHub) that downloads the songs into mp3 or WAV. I would not waste time on this...

**Comment by derblub** [comment]
Thanks, I'll check it out, but I really like your go implementation, especially the speed. Currently, I'm converting to mp3 with ffmpeg. It's just a problem when doing the conversion on a much slower cpu, since it's taking much longer.
