### ISSUE TITLE
unwrap() issue

### ISSUE THREAD

**Issue by wabiloo** [GuillemCastro/spotify-dl#6]
This is my first attempt at running with Rust, so I'm afraid I'm not confident in trying to figure it by myself...

I had an error on my Mac, when trying to run it in the following ways (after a successful `cargo build`):

```
cargo run spotify-dl --username MyUserName "https://open.spotify.com/playlist/1lCFgHBNwlqxuki0H9BxGL?si=3fe59aa036f54ef3"
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `target/debug/spotify-dl spotify-dl --username MyUserName 'https://open.spotify.com/playlist/1lCFgHBNwlqxuki0H9BxGL?si=3fe59aa036f54ef3'`
Password:
thread 'main' panicked at src/main.rs:149:62:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any idea what this might be?

**Comment by GuillemCastro** [comment]
For anyone else having this issue, there seems to be an issue in the regex parsing the spotify URL. The workaround right now is to remove the parameter `si=` at the end but keeping the question mark.
```
cargo run spotify-dl --username MyUserName "https://open.spotify.com/playlist/1lCFgHBNwlqxuki0H9BxGL?"
```

**Comment by qw3rtn** [comment]
Yes, I ran spotify-dl via cargo like this:

cargo run spotify-dl --username <user> "https://open.spotify.com/playlist/1lCFgHBNwlqxuki0H9BxGL?"
cargo run spotify-dl --username <user> "spotify:track:72NikOBusiF2xUToovTmxW"

Executing the binary file directly worked, thanks!
